services:
  postgres:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  label-studio:
    restart: unless-stopped
    image: heartexlabs/label-studio:latest
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files
      - DJANGO_DB=${DJANGO_DB}
      - POSTGRE_NAME=${POSTGRES_NAME}
      - POSTGRE_USER=${POSTGRES_USER}
      - POSTGRE_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRE_HOST=${POSTGRES_HOST}
      - POSTGRE_PORT=${POSTGRES_PORT}
    ports:
      - 8081:8080
    volumes:
      - label-studio-data:/label-studio/data
    depends_on:
      - postgres
volumes:
  pgdata:
    driver: local
  label-studio-data:
    driver: local
